"""add more coverage levels

Revision ID: db0436964e10
Revises: 5efb57139d4e
Create Date: 2017-03-03 09:51:25.789277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0436964e10'
down_revision = '5efb57139d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('coverage_30x', sa.Float(), nullable=True))
    op.add_column('sample', sa.Column('coverage_50x', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'coverage_50x')
    op.drop_column('sample', 'coverage_30x')
    # ### end Alembic commands ###
